config/routes.rb
Rails.application.routes.draw do


  resources :users do 
    resources :pins
  end

  get 'users/index'
  get 'users/show'

  match '/users', to: 'users#index', via: 'get'
  match '/users/:id', to: 'users#show', via: 'get'

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  
  root 'pages#home'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true

  has_one_attached :image do |image|
    image.variant :large, resize_to_fit: [1000, nil]
    image.variant :medium, resize_to_fit: [300, nil]
    image.variant :thumb, resize_to_fit: [nil, 150]
    image.variant :exibition, resize_to_fit: [nil, 750]
  end



  after_create_commit { broadcast_to_user }
  after_destroy_commit { broadcast_remove_to_user }

  private

  def broadcast_to_user
  user_name = "user_#{user.id}"
  # user_name = user.id

  broadcast_prepend_to user_name,
            target: 'pins',
            partial: 'pins/pin',
            locals: { pin: self }

  # broadcast_append_to ['admin', user_name],
  #           target: "controls_pin_#{id}",
  #           partial: 'pins/admin_controls',
  #           locals: { pin: self }

  broadcast_append_to [user&.to_gid_param],
              target: "controls_pin_#{id}",
              partial: 'pins/user_controls',
              locals: { pin: self, user:  }

  end

  def broadcast_remove_to_user
    user_name = "user_#{user.id}"

    broadcast_remove_to user_name,
    target: "pin_#{id}"
  end


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!


def show 

end

  def create
    @user = User.find(params[:user_id])
    @pin = @user.pins.build(pin_params)
    @pin.user = current_user
    @pin.save
    
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
  end

    private

  def pin_params
    params.require(:pin).permit(:title, :caption, :image, :user_id)
  end

end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_admin_controls.html.erb
<%= button_to "Admin Delete", 
user_pin_path(pin.user, pin),
method: :delete, data: { confirm: "Are you sure? "} %>

app/views/pins/_form.html.erb
<%= form_with model: Pin.new, url: user_pins_path(user) do |f| %>
    <%= f.text_field :title %>
    <%= f.text_area :caption %>
    <%= f.file_field :image %>
    <%= f.submit %>
<% end %>

app/views/pins/_pin.html.erb
  <%= turbo_frame_tag dom_id(pin) do %>

    <%= turbo_frame_tag(["controls", dom_id(pin)]) %>
    <%#= render "pins/admin_controls", pin: pin if admin %>

    <%= render "pins/user_controls", pin: pin if defined?(user) && user == pin.user %>

    <p>
      <%= "#{pin.user.username}: #{pin.title}" %>
      <%= image_tag url_for(pin.image.variant(:thumb)) if pin.image.attached? %>

    </p>

  <% end %>

app/views/pins/_user_controls.html.erb
<%= button_to "Creator Delete", 
    user_pin_path(pin.user, pin), 
    method: :delete, 
    data: { confirm: "Are you sure?" } %>

app/views/pins/create.turbo_stream.erb
  <%= turbo_stream.update Pin.new, "" %>

  <%= turbo_stream.prepend "pins" do %>
    <%= render @pin, user: @user %>
  <% end %>

  <%#= render_turbo_stream_flash_messages %>

app/views/pins/destroy.turbo_stream.erb
<%= turbo_stream.remove @pin %>
<%#= render_turbo_stream_flash_messages %>

app/views/pins/edit.html.erb
<h2>Edit pin</h2>

<%= link_to sanitize("&larr; Back to user"), user_path(@user) %>


<%= turbo_frame_tag @pin do %>
  <%= render "form", user: @user, pin: @pin %>
<% end %>
<br>

app/views/pins/index.html.erb
<p style="color: green"><%= notice %></p>

<h2>Pins</h2>
<%= tag.hr %>
  <% @pins.each do |pin| %>
    <%#= render pin %>
      <%= image_tag(pin.image.variant(:medium), class: "pic") if pin.image.attached? %>
<%= pin.user.username %> | <%= pin.id %> | <%= pin.title %> | <%= pin.caption %> | <%= pin.created_at %><br>



  <% end %>
<%= tag.hr %>

app/views/pins/new.html.erb
<h2>New pin</h2>

<%#= link_to sanitize("&larr; Back to user"), user_path(@user) %>

<%= turbo_frame_tag @pin do %>
| <%= link_to "Cancel", @user %>
  <%= render "form", user: @user, pin: @pin %>
<% end %>

<br>

app/views/pins/show.html.erb
<h2>Show pin </h2>

app/views/pins/update.turbo_stream.erb
<%= turbo_stream.replace @pin %>
<%#= render_turbo_stream_flash_messages %>