config/routes.rb
Rails.application.routes.draw do


  resources :users do 
    resources :pins
  end

  get 'users/index'
  get 'users/show'

  match '/users', to: 'users#index', via: 'get'
  match '/users/:id', to: 'users#show', via: 'get'

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  
  root 'pages#home'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pins, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum role: [:user, :moderator, :admin]
         after_initialize :set_default_role, :if => :new_record?
       
         def set_default_role
           self.role ||= :user
         end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
    @pin = @user.pins.build
    @pins = @user.pins.order created_at: :desc
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<h2>Profile</h2>
  <ul>
    <li>Admin : <%= user.admin? %></li>
    <li>ID User : <%= user.id %></li>
    <li>Name : <%= user.username %></li>
    <li>Email : <%= user.email %></li>
    <li>Role : <%= user.role %></li>
    <li>Rank : <%= user.rank %></li>
    <li>Created_at : <%= user.created_at %></li>
    <li><%= link_to "Edit", edit_user_registration_path if current_user == @user %></li>

  </ul>

  <div class="logout">
<%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" } %>
</div>

  <%= tag.hr %>
<%= render "pins/form", user: user %>

    <h2>Pins</h2>

  <div id="pins">
    <% user.pins.each do |pin| %>
      <%#= render "pins/pin", pin: pin, admin: current_user.admin?, user: current_user %>
      <%= render "pins/pin", pin: pin, user: current_user %>



    <% end %>
  </div>

app/views/users/index.html.erb
<h2>Users List</h2>

<table>
  <thead>
    <tr >
      <th>IDUser</th>
      <th>RoleUser</th>
      <th>Rank</th>
      <th>Name</th>
      <th>EmailUser</th>
      <th>UserPins</th>
      <th>UserCreated_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.role %></td>
      <td><%= user.rank %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.pin_ids %></td>
      <td><%= user.created_at %></td>

      current_user&.to_gid_param
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_registration_path if current_user == user %></td>
      <td>
      </td>

    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
 <p style="color: green"><%= notice %></p>
<%= turbo_stream_from dom_id(@user) %>

<%= turbo_stream_from current_user&.to_gid_param %>

<%# if current_user&.admin? %>
  <%#= turbo_stream_from ["admin", dom_id(@user)], id: "admin" %>
<%# end %>
 
 <%= render partial: @user, user: :user %>
 
 <%= tag.hr %>
<%#= turbo_stream_from dom_id(@user) %>

<%= current_user&.to_gid_param %>