config/routes.rb
Rails.application.routes.draw do


  resources :users do 
    resources :pins
  end

  get 'users/index'
  get 'users/show'

  match '/users', to: 'users#index', via: 'get'
  match '/users/:id', to: 'users#show', via: 'get'

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  
  root 'pages#home'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_alerts.html.erb
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<%= tag.hr %>
<%= link_to "Users", users_path  %>

app/views/layouts/_header.html.erb
<div class="header">
<% if current_user %>
<%= link_to "Home", root_path %> - <%#= link_to "Pins", pins_path %>

    <% if user_signed_in? %>
      <%= link_to current_user.username, user_path(current_user.id) %>
    <% end %>

<% else %>
  <%= link_to "Login", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% end %>
<%= tag.hr %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Usercurrent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <script async src="https://ga.jspm.io/npm:es-module-shims@1.8.2/dist/es-module-shims.js" data-turbo-track="reload"></script>
    <%= javascript_importmap_tags %>
  </head>
    <p style="background-color: yellow; width: 95%; margin: auto">
      <%= debug(params) if Rails.env.development? %>
    </p>
  <body>
    <%= render partial: "layouts/header" %>
      <main class="container">
        <%= render partial: "layouts/alerts" %>
            <%= yield %>
      </main>
    <%= render partial: "layouts/footer" %>
  </body>
</html>